### ISSUE TITLE
Is there a way to move the location of the widget?

### ISSUE THREAD

**Issue by Energy0124** [akiroz/Live2D-Widget#4]
as title :)

**Comment by CRiMSONxx** [comment]
its invisible, around the head of the widget, try to move the cursor until it changes from hand to default cursor
if you cant find it in package.json change the
"frame": false,
"transparent": true,
to
"frame": true,
"transparent": false,

**Comment by Energy0124** [comment]
Thanks a lot for your help! It works 👍
