### ISSUE TITLE
LatencyInfo vector size 102 is too big

### ISSUE THREAD

**Issue by Xwilarg** [akiroz/Live2D-Widget#5]
Hi,

I followed the steps to launch this but when I'm trying it display
`[21246:21246:1122/144300.721912:ERROR:latency_info.cc(144)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big.`
in the console many times and nothing happen.

I'm on Ubuntu 18.04.1 LTS.

**Comment by CRiMSONxx** [comment]
hi, im pretty sure this project already discontinued, therefore i suggest using other plugins, thank you

**Comment by Xwilarg** [comment]
Thanks for your help :)
